### PR TITLE
[WIP] C, C++, Python, Go and Lua books

### PR DESCRIPTION
**Pull request by Delta456**
Solves https://github.com/developersIndia/wiki/issues/4

### CODE REVIEW

**Comment by Bhupesh-V** [comment]
@Delta456  you could also Create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/), instead of adding [WIP] :sweat_smile:

**Comment by Bhupesh-V** [comment]
@Delta456 whats the status on this one, should I merge ?

**Comment by Delta456** [comment]
You can merge this I guess. I don't have time currently; Exams 😅

**Comment by Bhupesh-V** [comment]
@all-contributors please add @Delta456  for content

**Pull request merged**
